import { detectShape } from './schema-infer.js';
import type { EnvDocument, EnvEntry, EnvValueShape } from './kinds.js';

/**
 * NekoEnv Pro code generation. Backs the declared Pro exporters
 * `env.export.types.typescript`, `env.export.types.zod`,
 * `env.export.docs.data-dictionary`, and `env.export.compose.dotenv-stack`
 * (see docs/tools/nekoenv.md §4).
 *
 * Every function is a pure, deterministic transform of parsed
 * `env.document` value(s) — no network, no clock, no filesystem, no
 * process spawning. Value-shape categorisation reuses the free
 * `detectShape` helper so the generated types line up with the schema the
 * free tier already shows. `types.*` describe a single environment;
 * `data-dictionary` and `compose.dotenv-stack` are cross-document.
 */

/** A parsed env document paired with its source artifact id. */
export interface NamedEnvDoc {
  readonly id: string;
  readonly doc: EnvDocument;
}

/** A valid TS/JS identifier? Bare keys can be emitted unquoted. */
function isSafeIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

function quoteKey(key: string): string {
  return isSafeIdentifier(key) ? key : JSON.stringify(key);
}

/**
 * Distinct entries of a document, last-occurrence-wins (matching dotenv
 * loader precedence and the free schema/canonical exporters). `Map.set`
 * on an existing key updates the value while preserving its original
 * position, so iteration order is first-occurrence with the last value.
 */
function lastWins(doc: EnvDocument): Map<string, EnvEntry> {
  const m = new Map<string, EnvEntry>();
  for (const e of doc.entries) m.set(e.key, e);
  return m;
}

const EMPTY_DOC: EnvDocument = { entries: [], lines: [] };

// --- TypeScript: typed ProcessEnv-shaped interface -------------------------

/** Shapes worth noting in a JSDoc comment (more specific than `string`). */
const SHAPE_NOTE: Partial<Record<EnvValueShape, string>> = {
  boolean: 'boolean',
  integer: 'integer',
  decimal: 'decimal',
  url: 'url',
};

/**
 * `env.export.types.typescript` — a typed `ProcessEnv`-shaped interface.
 *
 * Emits a `NodeJS.ProcessEnv` global augmentation (the standard "typed
 * process.env" pattern) so `process.env.KEY` is known and string-typed.
 * Every member is `string` because dotenv values are strings at runtime;
 * the inferred value shape is attached as a JSDoc note where it is more
 * specific than `string`, documenting intent without lying about the type.
 */
export function toProcessEnvInterface(doc: EnvDocument): string {
  const entries = lastWins(doc);
  const lines: string[] = [
    '// Generated by NekoEnv from your .env — a typed ProcessEnv augmentation',
    '// so process.env.KEY is known and string-typed. Values are strings at',
    '// runtime; the inferred shape is noted per key where more specific.',
    'export {};',
    '',
    'declare global {',
    '  namespace NodeJS {',
    '    interface ProcessEnv {',
  ];
  for (const [key, entry] of entries) {
    const note = SHAPE_NOTE[detectShape(entry.value)];
    if (note !== undefined) lines.push(`      /** ${note} */`);
    lines.push(`      ${quoteKey(key)}: string;`);
  }
  lines.push('    }', '  }', '}', '');
  return lines.join('\n');
}

// --- Zod: schema validating a loaded env -----------------------------------

/** Map an inferred value shape to a Zod validator source string. */
function zodForShape(value: string): string {
  switch (detectShape(value)) {
    case 'integer':
      return 'z.coerce.number().int()';
    case 'decimal':
      return 'z.coerce.number()';
    case 'url':
      return 'z.string().url()';
    case 'boolean':
      return "z.enum(['true', 'false', 'TRUE', 'FALSE'])";
    case 'empty':
    case 'string':
      return 'z.string()';
  }
}

/**
 * `env.export.types.zod` — a Zod schema validating a loaded env. Each key
 * gets a validator derived from its inferred shape: numbers coerce from
 * their string form, URLs are URL-validated, booleans are constrained to
 * the dotenv boolean spellings, everything else is `z.string()`. Pairs
 * with the TypeScript export; `Env` is the inferred parsed type.
 */
export function toZodEnvSchema(doc: EnvDocument): string {
  const entries = lastWins(doc);
  const fields = [...entries].map(
    ([key, entry]) => `  ${quoteKey(key)}: ${zodForShape(entry.value)},`,
  );
  const body = fields.length === 0 ? 'z.object({})' : `z.object({\n${fields.join('\n')}\n})`;
  return [
    "import { z } from 'zod';",
    '',
    '// Generated by NekoEnv. Validates (and coerces) a loaded env against the',
    '// shapes inferred from your .env. Tighten as your real contract evolves.',
    `export const envSchema = ${body};`,
    '',
    'export type Env = z.infer<typeof envSchema>;',
    '',
  ].join('\n');
}

// --- Data dictionary: cross-document presence matrix -----------------------

function escapePipe(s: string): string {
  return s.replace(/\|/g, '\\|');
}

/**
 * `env.export.docs.data-dictionary` — a cross-document markdown dictionary:
 * every key seen across the supplied environments, a presence matrix
 * (which environments define it), and a comment-derived description (the
 * inline `# comment` on the key, first non-empty occurrence across
 * documents in order). No values are emitted — this is documentation, not
 * a secret dump.
 */
export function toDataDictionary(docs: readonly NamedEnvDoc[]): string {
  if (docs.length === 0) {
    return '# NekoEnv data dictionary\n\n(no environments)\n';
  }
  const perDoc = docs.map((d) => lastWins(d.doc));

  // Union of keys across all documents, sorted for a stable dictionary.
  const keys = new Set<string>();
  for (const m of perDoc) for (const k of m.keys()) keys.add(k);
  const sortedKeys = [...keys].sort();

  const describe = (key: string): string => {
    for (const m of perDoc) {
      const e = m.get(key);
      if (e?.trailingComment) return e.trailingComment;
    }
    return '';
  };

  const envLabel = (i: number): string => `env ${i + 1}`;
  const out: string[] = ['# NekoEnv data dictionary', ''];
  out.push(`Keys across ${docs.length} environment${docs.length === 1 ? '' : 's'}:`, '');
  for (const [i, d] of docs.entries()) out.push(`- ${envLabel(i)}: \`${d.id}\``);
  out.push('');

  const cols = ['key', 'description'];
  for (const [i] of docs.entries()) cols.push(envLabel(i));
  out.push(`| ${cols.join(' | ')} |`, `| ${cols.map(() => '---').join(' | ')} |`);
  for (const key of sortedKeys) {
    const presence = perDoc.map((m) => (m.has(key) ? '✓' : '—'));
    out.push(`| \`${key}\` | ${escapePipe(describe(key))} | ${presence.join(' | ')} |`);
  }
  out.push('');
  return out.join('\n');
}

// --- Compose: multi-environment composite ----------------------------------

/** A YAML double-quoted scalar — JSON string escaping is a safe subset. */
function yamlScalar(value: string): string {
  return JSON.stringify(value);
}

/**
 * `env.export.compose.dotenv-stack` — a multi-environment composite for
 * Docker Compose and Kubernetes ConfigMap workflows.
 *
 * The supplied environments are overlaid (later documents override earlier
 * keys — the dotenv-stack convention `.env` < `.env.local` <
 * `.env.production`) and emitted as both a Compose `environment:` block and
 * a ConfigMap `data:` block. Pure text: it references files/values, it
 * never reads the filesystem or spawns a process.
 */
export function toComposeStack(docs: readonly NamedEnvDoc[]): string {
  const merged = new Map<string, string>();
  for (const d of docs) for (const e of d.doc.entries) merged.set(e.key, e.value);
  const keys = [...merged.keys()].sort();

  const out: string[] = [
    '# NekoEnv multi-environment composite',
    `# Composited from ${docs.length} environment document(s); later layers override earlier keys.`,
  ];
  if (docs.length > 0) {
    out.push('# layers (low → high precedence):');
    for (const [i, d] of docs.entries()) out.push(`#   ${i + 1}. ${d.id}`);
  }
  out.push('');

  out.push('# ---- Docker Compose (services.<name>.environment) ----', 'services:', '  app:', '    environment:');
  if (keys.length === 0) out.push('      {}');
  for (const k of keys) out.push(`      ${k}: ${yamlScalar(merged.get(k)!)}`);
  out.push('');

  out.push(
    '# ---- Kubernetes ConfigMap ----',
    'apiVersion: v1',
    'kind: ConfigMap',
    'metadata:',
    '  name: app-config',
    'data:',
  );
  if (keys.length === 0) out.push('  {}');
  for (const k of keys) out.push(`  ${k}: ${yamlScalar(merged.get(k)!)}`);
  out.push('');

  return out.join('\n');
}

// `EMPTY_DOC` is exported so exporters can render a stable empty result.
export { EMPTY_DOC };
