import { GLOBAL_SECTION, type IniSection, type ParsedIni } from './kinds.js';

/**
 * NekoINI Pro generators. Back the declared Pro exporters
 * `ini.export.env` (pro entitlement `convert.env`) and `ini.export.toml`
 * (pro entitlement `convert.toml`).
 *
 * Both are pure, deterministic functions of a parsed `ini.parsed` document —
 * no network, no clock, no premium engine. INI values are raw strings and
 * stay raw strings here (no type coercion — that's the advertising-only
 * `infer.types` capability, and matches the manifest's out-of-scope note);
 * the conversions are structural format mappings only.
 */

/** Sections in a stable order: the global (pre-section) block first. */
function orderedSections(ini: ParsedIni): readonly IniSection[] {
  const global = ini.sections.filter((s) => s.name === GLOBAL_SECTION);
  const named = ini.sections.filter((s) => s.name !== GLOBAL_SECTION);
  return [...global, ...named];
}

// --- .env ------------------------------------------------------------------

/** Uppercase a name and replace any non-identifier run with a single `_`. */
function envToken(name: string): string {
  return name
    .trim()
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();
}

/** A dotenv variable name: `KEY` globally, `SECTION_KEY` within a section. */
function envName(section: string, key: string): string {
  const k = envToken(key);
  return section === GLOBAL_SECTION ? k : `${envToken(section)}_${k}`;
}

/** Quote a dotenv value only when it carries whitespace, `#`, or quotes. */
function envValue(value: string): string {
  if (value === '') return '';
  if (/[\s"'#]/.test(value)) {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
  }
  return value;
}

/**
 * `ini.export.env` — flatten the INI into dotenv assignments. Global keys
 * become `KEY=value`; section keys become `SECTION_KEY=value` (both
 * upper-cased, non-identifier characters collapsed to `_`). Values are kept
 * as raw strings, quoted only when necessary. A leading comment documents the
 * lossy section→prefix flattening.
 */
export function toDotenv(ini: ParsedIni): string {
  const out: string[] = [
    '# Generated by NekoINI from your INI document.',
    '# Section keys are flattened to SECTION_KEY=value; values are raw strings.',
    '',
  ];
  for (const section of orderedSections(ini)) {
    if (section.entries.length === 0) continue;
    if (section.name !== GLOBAL_SECTION) out.push(`# [${section.name}]`);
    for (const e of section.entries) {
      out.push(`${envName(section.name, e.key)}=${envValue(e.value)}`);
    }
    out.push('');
  }
  return out.join('\n').trimEnd() + '\n';
}

// --- TOML ------------------------------------------------------------------

const BARE_KEY_RE = /^[A-Za-z0-9_-]+$/;

/** A TOML key: bare when safe, else a basic-string quoted key. */
function tomlKey(key: string): string {
  return BARE_KEY_RE.test(key) ? key : tomlString(key);
}

/** A TOML basic string (INI values are always strings — no type coercion). */
function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t')
    .replace(/\r/g, '\\r');
  return `"${escaped}"`;
}

/**
 * `ini.export.toml` — emit the INI as TOML. Global entries become top-level
 * `key = "value"` pairs (before any table header, as TOML requires); each
 * named section becomes a `[section]` table. Values are emitted as TOML
 * basic strings — NekoINI never coerces INI values to numbers/booleans.
 */
export function toToml(ini: ParsedIni): string {
  const blocks: string[] = [];

  const global = ini.sections.find((s) => s.name === GLOBAL_SECTION);
  if (global && global.entries.length > 0) {
    blocks.push(global.entries.map((e) => `${tomlKey(e.key)} = ${tomlString(e.value)}`).join('\n'));
  }

  for (const section of ini.sections) {
    if (section.name === GLOBAL_SECTION) continue;
    const header = `[${section.name.split('.').map(tomlKey).join('.')}]`;
    const lines = [header, ...section.entries.map((e) => `${tomlKey(e.key)} = ${tomlString(e.value)}`)];
    blocks.push(lines.join('\n'));
  }

  return blocks.join('\n\n');
}
